<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationDefaultFont>Segoe UI, 9.75pt</ApplicationDefaultFont>
    <RootNamespace>PharmacyIS.UI</RootNamespace>
    <AssemblyName>PharmacyIS</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PharmacyIS.Domain\PharmacyIS.Domain.csproj" />
    <ProjectReference Include="..\PharmacyIS.Data\PharmacyIS.Data.csproj" />
    <ProjectReference Include="..\PharmacyIS.Services\PharmacyIS.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
